apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: nginx-automation
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: FluxCD Bot
        email: fluxcd@users.noreply.github.com
      messageTemplate: |
        Update image to {{ .Updated.Image }}
    push:
      branch: main
  update:
    strategy: Setters
    path: ./apps
