apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: nginx-automation
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    commit:
      author:
        email: fluxcd@users.noreply.github.com
        name: fluxcd
      messageTemplate: |
        Automated image update: {{ .Changed.Image.Repository }}:{{ .Changed.Image.Tag }}
    push:
      branch: main
  update:
    path: ./apps
