apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: nginx-automation
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    commit:
      author:
        email: fluxcd@users.noreply.github.com
        name: fluxcd
      messageTemplate: |
        Automated image update
      
        {{ range .Changed.Objects -}}
        {{ range $resource, $changes := . -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
          {{- range $_, $change := $changes }}
            * {{ $change.OldValue }} -> {{ $change.NewValue }}
          {{ end -}}
        {{ end -}}
        {{ end -}}
    push:
      branch: main
  update:
    path: ./apps
