apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: nginx-automation
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    commit:
      author:
        name: FluxCD Bot
        email: fluxcd@users.noreply.github.com
    push:
      branch: main
  update:
    path: ./apps
